build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base-python:3.11-alpine3.18"
  amd64: "ghcr.io/home-assistant/amd64-base-python:3.11-alpine3.18"
squash: false
labels:
  org.opencontainers.image.title: "HIRIS"
  org.opencontainers.image.description: "Home Intelligent Reasoning & Integration System"
  org.opencontainers.image.source: "https://github.com/paolobets/hiris"
  org.opencontainers.image.licenses: "MIT"
